const Bank_list = [
    "Access Bank",
    "Accion Microfinance Bank",
    "Advans La Fayette Microfinance Bank",
    "Citibank Nigeria",
    "Coronation Merchant Bank",
    "Covenant Microfinance Bank",
    "Dot Microfinance Bank",
    "Ecobank Nigeria",
    "Empire Trust Microfinance Bank",
    "FairMoney Microfinance Bank",
    "FBNQuest Merchant Bank",
    "Fidelity Bank",
    "Fina Trust Microfinance Bank",
    "Finca Microfinance Bank ",
    "First Bank of Nigeria ",
    "First City Monument Bank",
    "FSDH Merchant Bank",
    "Globus Bank",
    "Guaranty Trust Bank",
    "Heritage Bank",
    "Infinity Microfinance Bank",
    "Jaiz Bank",
    "Keystone Bank",
    "Kuda Bank",
    "LOTUS BANK",
    "Mint Finex MFB",
    "Mkobo MFB",
    "Moniepoint Microfinance Bank",
    "Mutual Trust Microfinance Bank",
    "Nova Merchant Bank",
    "Opay",
    "Optimus Bank",
    "Palmpay",
    "Parallex Bank",
    "Peace Microfinance Bank",
    "Pearl Microfinance Bank",
    "Polaris Bank",
    "PremiumTrust Bank",
    "Providus Bank",
    "Rand Merchant Bank",
    "Raven Bank",
    "Rephidim Microfinance Bank",
    "Rex Microfinance Bank",
    "Rubies Bank",
    "Shepherd Trust Microfinance Bank",
    "Sparkle Bank",
    "Stanbic IBTC Bank",
    "Standard Chartered Bank",
    "Sterling Bank",
    "SunTrust Bank",
    "TAJBank",
    "Titan Trust Bank",
    "Titan Trust Bank",
    "Union Bank of Nigeria",
    "United Bank For Africa",
    "Unity Bank",
    "VFD Microfinance Bank",
    "Wema Bank",
    "Zenith Bank",
]

export default Bank_list